# Generated by Django 3.1.6 on 2021-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('9AM to 10AM', '9AM to 10AM'), ('11am to 12pm', '11am to 12pm'), ('1pm to 2pm', '1pm to 2pm'), ('4pm to 5pm', '4pm to 5pm'), ('6pm to 7pm', '6pm to 7pm'), ('7pm to 8pm', '7pm to 8pm')], default='Choose Your Schedule', max_length=15)),
                ('patient_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
